apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modbus-exporter.fullname" . }}
  labels:
    {{- include "modbus-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "modbus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "modbus-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "modbus-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/modbus_exporter"]
          args:
          - "--config.file=/etc/modbus_exporter/modbus.yml"
          - "--log.level={{ .Values.log.level | default ("info") }}"
          - "--log.format={{ .Values.log.format | default ("logfmt") }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9602
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9602
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: configfile
            mountPath: /etc/modbus_exporter/
            # mountPath: /app/modbus.yml
            # subPath: modbus.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: configfile
        configMap:
          {{- if not .Values.configMapFile }}
          name: {{ include "modbus-exporter.fullname" . }}
          {{- else }}
          name: {{ .Values.configMapFile }}
          {{- end }}
