{{- $fullName := include "modbus-exporter.fullname" . -}}
{{- $endpointsCommonConfig := .Values.serviceMonitor.endpointsCommonConfig -}}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "modbus-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "modbus-exporter.labels" . | nindent 6 }}
  endpoints:
  {{- range .Values.serviceMonitor.endpointsConfig }}
  - port: metrics
    path: "/modbus"
{{ toYaml . | indent 4 }}
    {{/*path: "/modbus&target=1.2.3.4:502" */}}
    {{ toYaml $endpointsCommonConfig | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceMonitorExporterItself.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}-self-monitor
  labels:
    {{- include "modbus-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitorExporterItself.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitorExporterItself.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "modbus-exporter.labels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: "/metrics"
{{- end }}